language: java

sudo: false # faster builds

install: true

jdk:
  - openjdk8

notifications:
  email: false

script:
  - mvn install -D skipTests=true -D maven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura -D cobertura.report.format=xml -D maven.javadoc.skip.true