language: java

sudo: false # faster builds

install: true

jdk:
  - openjdk8

notifications:
  email: false

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip.true