language: java

sudo: false # faster builds

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - openjdk8

notifications:
  email: false

script:
  - export TZ=Europe/Warsaw
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip.true